/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pertemuan8;

import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Login extends javax.swing.JFrame {

    User[] registeredUsers ={
        new User("b24@gmail.com","admin"),
        new User( "p12@gmail.com", "ayang"),
        new User("v0@gmail.com", "hehe")
    };
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Nama_User = new javax.swing.JTextField();
        Masukan_Password = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN AE");
        getContentPane().setLayout(null);

        User.setText("E-mail");
        getContentPane().add(User);
        User.setBounds(17, 9, 33, 16);

        Password.setText("Password");
        getContentPane().add(Password);
        Password.setBounds(17, 38, 70, 16);

        Nama_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_UserActionPerformed(evt);
            }
        });
        getContentPane().add(Nama_User);
        Nama_User.setBounds(103, 6, 268, 22);
        getContentPane().add(Masukan_Password);
        Masukan_Password.setBounds(103, 35, 268, 22);

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(300, 70, 72, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\Wallpaper\\Wallpaper dark.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        
          String email = Nama_User.getText();
          String password = Masukan_Password.getText();
            
          for(User u : registeredUsers) {
                
            boolean loginBerhasil = u.verify(email, password);
                
            if(loginBerhasil) {
                JOptionPane.showMessageDialog(null,"Login Berhasil!");
                break;
            }
            else {
                 JOptionPane.showMessageDialog(null,"Login Gagal!");
                 
            }
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void Nama_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_UserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField Masukan_Password;
    private javax.swing.JTextField Nama_User;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel User;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
